### ISSUE TITLE
Buffer is all ways empty & Player crash

### ISSUE THREAD

**Issue by Apollo2000** [romanvm/kodi.yatp#24] opened 2016-01-05 09:46 UTC
Hi,

First you need great work! Very good coding. 

I did all like wiki:
1. add_torrent => OK
2. check_torrent_added => True
3. get_last_added_torrent => TorrentInfo
4. buffer_file(0) => OK
5. prioritize_file(0,7) => OK
Now in loop i am checking get_buffer_percent and check_buffering_complete.
Like you can see in log, also after downloading 250MB i still get:
get_buffer_percent => 0
check_buffering_complete => False

Buffering Bad: http://pastebin.com/5EjPgGbk

Now i try doing my own buffering (base on percent of total file size), and when finish buffer i run player:
url=http://127.0.0.1:8668/stream/12.Years.A.Slave.2013.720p.BluRay.x264-BLOW/12.Years.A.Slave.2013.720p.BluRay.x264-BLOW.mkv
listitem = xbmcgui.ListItem(path=url)
listitem.setInfo(type="Video", infoLabels={ "Title": label })
xbmcplugin.setResolvedUrl(handle, True, listitem)

And player freeze computer and then give error

Player crash: http://pastebin.com/q7d69Pzn

Thank's man.

**Comment by romanvm** [comment] 2016-01-05 12:55
Sorry, but I don't get what you are trying to accomplish. If you want to create a custom player based on YATP first read the Wiki on how to use JSON-RPC and see how it is implemented in YATP client part. Why you are using `prioritize_file` at all? This method is not meant for streaming but for general torrent management.

Also I don't provide support for someone else's code unless they want to create a PR for YATP to add a feature or fix a bug.

**Comment by Apollo2000** [comment] 2016-01-05 13:23
I want to create a player like pulsar. 
torrent -> stream -> play. That all.
I read wiki but no info about creating player using JSON-RPC.

**Comment by romanvm** [comment] 2016-01-05 14:25
The Wiki page about JSON-RPC provides a recommended sequence of requests for playing a torrent. Also, as I've said, YATP client code can be used as a starting point.

Also I've checked your torrent from log. It seems that this tracker has some problems with torrents that are set to partial download, i.e. if priorities for some or all pieces are set to 0. I've tried a quick fix for initial buffering but further download speed is still very low for continuous playback.

**Comment by Apollo2000** [comment] 2016-01-05 16:00
I change tracker to http://php-tracker.org/ but still not getting data.
I using normal torrent client and i get 1-2Mb/s.

I try using yatp for playing the torrent (Play .torrent file) i get 20-30Kb/s. 

That without using my player.
You can see that yatp send port =0 sometime.
And same file got 3 seeds (1Gbps seeds)
http://i67.tinypic.com/2afwz6a.png

Log: http://pastebin.com/PsECu1VE

**Comment by Apollo2000** [comment] 2016-01-05 18:33
I install OpenTracker, same result. 

Same machine, Xixati client 2Mb/s, yatp 0 (using your downloader directly, no RPC)
http://i64.tinypic.com/28qw2vm.png

**Comment by romanvm** [comment] 2016-01-07 08:32
Honestly, I don't see what can be done here. You seem to use some custom setup, and I'm not sure that I can reproduce your issues. YATP works with most popular torrent trackers in the Internet, and I'm using it regularly myself to watch my favorite TV-shows. But it is not guaranteed that it will work with *every* tracker. Moreover, all torrent operations are controlled by the binary libtorrent library which is a closed "black box" for me. So I'm closing this issue because it cannot be reproduced/solved under the circumstances.

**Closed by romanvm** 2016-01-07 08:32 UTC
